node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    def scannerHome = tool 'SONAR_RUNNER_HOME';
        withSonarQubeEnv() {
        bat "${scannerHome}/bin/sonar-scanner"
    }
  }

  stage('Build') {
           git 'https://github.com/VYermakovich/Mobile_Android_Onliner.git'
           bat "mvn clean verify sonar:sonar
                  -Dsonar.projectKey=Mobile
                  -Dsonar.host.url=http://localhost:9000
                  -Dsonar.login=4b18cd83df712ec25055a7a088ad2e6ec995680c"
  }

 stage('Report') {
            bat "allure generate allure-report --clean -o allure-report || true && allure report open -o allure-report"
             script {
                     allure([
                             includeProperties: false,
                             jdk: '',
                             properties: [],
                             reportBuildPolicy: 'ALWAYS',
                             results: [[path: '../allure-results']]
                     ])
             }
 }
}